### ISSUE TITLE
Error in docker log

### ISSUE THREAD

**Issue by euven** [zrrrzzt/docker-unoconv-webservice#7]
I'm seeing the following in my docker logs after pulling and running the latest image:
`Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'filename' of undefined
    at module.exports.handleUpload.file.on.data.file.on (/unoconvservice/handlers/index.js:13:37)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/unoconvservice/node_modules/hapi/lib/handler.js:99:36)
    at /unoconvservice/node_modules/hapi/lib/handler.js:30:23
    at internals.Protect.run.finish [as run] (/unoconvservice/node_modules/hapi/lib/protect.js:62:12)
    at exports.execute.finalize (/unoconvservice/node_modules/hapi/lib/handler.js:24:22)
    at each (/unoconvservice/node_modules/hapi/lib/request.js:380:16)
    at iterate (/unoconvservice/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/unoconvservice/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth.test.internals.Auth.payload.finalize (/unoconvservice/node_modules/hapi/lib/auth.js:235:16)
    at each (/unoconvservice/node_modules/hapi/lib/request.js:380:16)`

Any ideas?

**Comment by euven** [comment]
I get this when trying to convert an .rtf file to .pdf

**Comment by euven** [comment]
Apologies, I was being an idiot with my curl request - nothing to see here! :D

**Comment by sabahang** [comment]
@eugeneventer excuse the noobie question: how do you check the logs?
