### ISSUE TITLE
Fail to run after upgrading node version

### ISSUE THREAD

**Issue by vincentkwok** [zrrrzzt/docker-unoconv-webservice#9]
```sh
unoconv_1     | /unoconvservice/node_modules/hoek/lib/index.js:736
unoconv_1     |     throw new Error(msgs.join(' ') || 'Unknown error');
unoconv_1     |     ^
unoconv_1     | 
unoconv_1     | Error: Server timeout must be shorter than socket timeout: POST /unoconv/{format}
unoconv_1     |     at Object.exports.assert (/unoconvservice/node_modules/hoek/lib/index.js:736:11)
unoconv_1     |     at new module.exports.internals.Route (/unoconvservice/node_modules/hapi/lib/route.js:69:10)
unoconv_1     |     at module.exports.internals.Connection.internals.Connection._addRoute (/unoconvservice/node_modules/hapi/lib/connection.js:413:19)
unoconv_1     |     at module.exports.internals.Connection.internals.Connection._route (/unoconvservice/node_modules/hapi/lib/connection.js:405:18)
unoconv_1     |     at module.exports.internals.Plugin.internals.Plugin._apply (/unoconvservice/node_modules/hapi/lib/plugin.js:598:14)
unoconv_1     |     at module.exports.internals.Plugin.internals.Plugin.route (/unoconvservice/node_modules/hapi/lib/plugin.js:568:10)
unoconv_1     |     at Object.exports.register (/unoconvservice/index.js:6:10)
unoconv_1     |     at Object.target [as register] (/unoconvservice/node_modules/joi/lib/types/object/index.js:76:34)
unoconv_1     |     at each (/unoconvservice/node_modules/hapi/lib/plugin.js:310:14)
unoconv_1     |     at iterate (/unoconvservice/node_modules/items/lib/index.js:36:13)
```

**Comment by vincentkwok** [comment]
Great thanks
